# Generated by Django 4.0.5 on 2022-07-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.page')),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='book',
        ),
        migrations.RemoveField(
            model_name='text',
            name='fragment',
        ),
        migrations.RemoveField(
            model_name='text',
            name='page',
        ),
        migrations.RemoveField(
            model_name='textorder',
            name='next',
        ),
        migrations.RemoveField(
            model_name='textorder',
            name='prev',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='ScanFragment',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='TextOrder',
        ),
    ]
