# Generated by Django 4.1 on 2023-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="pages/"),
        ),
        migrations.AlterField(
            model_name="page",
            name="image_url",
            field=models.TextField(blank=True),
        ),
    ]
