# Generated by Django 4.0.5 on 2022-07-06 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_pagetext_remove_text_book_remove_text_fragment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
