# Generated by Django 4.0.5 on 2022-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_pagetext_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
