# Generated by Django 4.2.4 on 2023-09-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_historicalpage_processed_page_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpage",
            name="text_size",
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="text_size",
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
