# Generated by Django 4.2.4 on 2023-09-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_historicalpage_text_size_page_text_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpage",
            name="processed",
        ),
        migrations.RemoveField(
            model_name="page",
            name="processed",
        ),
        migrations.AddField(
            model_name="historicalpage",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Идет распознавание"),
                    ("redy", "Готово к вычитке"),
                    ("in_progress", "В процессе вычитки"),
                    ("done", "Вычитано"),
                ],
                default="processing",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Идет распознавание"),
                    ("redy", "Готово к вычитке"),
                    ("in_progress", "В процессе вычитки"),
                    ("done", "Вычитано"),
                ],
                default="processing",
                max_length=100,
            ),
        ),
    ]
