# Generated by Django 4.2.6 on 2023-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0009_alter_page_book_squashed_0013_alter_historicalpage_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_pages_in_pdf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
