# Generated by Django 4.2.6 on 2023-11-20 15:29
from PyPDF2 import PdfReader
from django.db import migrations
from django.db.migrations import RunPython


def fill_total_pages_in_pdf(apps, schema_editor):
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all():
        book.total_pages_in_pdf = len(PdfReader(book.pdf).pages)
        book.save()


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0014_book_total_pages_in_pdf'),
    ]

    operations = [
        RunPython(fill_total_pages_in_pdf, reverse_code=migrations.RunPython.noop),
    ]
