# Generated by Django 4.2.7 on 2023-12-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0015_auto_20231120_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpage',
            name='number',
            field=models.IntegerField(verbose_name='Порядковый номер страницы'),
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='status',
            field=models.CharField(
                choices=[
                    ('processing', 'Распознавание'),
                    ('redy', 'Распознано'),
                    ('in_progress', 'Вычитка'),
                    ('formatting', 'Форматирование'),
                    ('check', 'Проверка'),
                    ('done', 'Завершено'),
                ],
                default='processing',
                max_length=100,
                verbose_name='Статус',
            ),
        ),
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.IntegerField(verbose_name='Порядковый номер страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(
                choices=[
                    ('processing', 'Распознавание'),
                    ('redy', 'Распознано'),
                    ('in_progress', 'Вычитка'),
                    ('formatting', 'Форматирование'),
                    ('check', 'Проверка'),
                    ('done', 'Завершено'),
                ],
                default='processing',
                max_length=100,
                verbose_name='Статус',
            ),
        ),
    ]
