# Generated by Django 4.2.7 on 2023-12-25 11:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0019_auto_20231217_1437'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
