# Generated by Django 4.2.7 on 2023-12-28 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0020_alter_page_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[],
        ),
    ]
