# Generated by Django 4.2.7 on 2025-12-04 06:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0021_alter_page_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                (
                    'repo',
                    models.CharField(
                        help_text='Формат: username/repository', max_length=200, verbose_name='Репозиторий'
                    ),
                ),
                ('branch', models.CharField(default='main', max_length=100, verbose_name='Ветка')),
                ('directory', models.CharField(default='books', max_length=200, verbose_name='Директория')),
            ],
            options={
                'verbose_name': 'Источник экспорта',
                'verbose_name_plural': 'Источники экспорта',
                'db_table': '"book"."export_source"',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='export_source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='books',
                to='books.exportsource',
                verbose_name='Источник экспорта',
            ),
        ),
    ]
