# Generated by Django 4.2.7 on 2025-12-11

from django.db import migrations, models


def populate_export_name(apps, schema_editor):
    """Populate export_name from book name for existing books."""
    Book = apps.get_model('books', 'Book')
    for book in Book.objects.all():
        book.export_name = book.name
        book.save(update_fields=['export_name'])


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0022_exportsource_book_export_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='export_name',
            field=models.CharField(
                default='',
                help_text='Имя файла при экспорте в GitHub (без расширения)',
                max_length=200,
                verbose_name='Имя файла для экспорта',
            ),
        ),
        migrations.RunPython(populate_export_name, migrations.RunPython.noop),
    ]
