# Generated by Django 4.2.7 on 2025-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0024_remove_duplicate_pages_add_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='export_pages',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Интервал страниц для экспорта (например, 4-15). Пустое значение - экспорт всех страниц.',
                max_length=50,
                verbose_name='Страницы для экспорта',
            ),
        ),
    ]
