# Generated by Django 4.2.7 on 2026-02-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0025_add_export_pages_to_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Заблокирована'),
        ),
    ]
