# Generated by Django 4.2.7 on 2026-02-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_bookmark_name'),
        ('books', '0029_page_ocr_data'),
    ]

    operations = []
