# Generated by Django 4.2.5 on 2023-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersettings_customuser_text_size"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersettings",
            options={
                "verbose_name": "Настройки аккаунта",
                "verbose_name_plural": "Настройки аккаунта",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="text_size",
            field=models.IntegerField(
                blank=True, default=12, null=True, verbose_name="Размер текста"
            ),
        ),
    ]
