# Generated by Django 4.2.7 on 2023-12-17 14:30

from django.db import migrations


def create_statuses(apps, schema_editor):
    PageStatus = apps.get_model('accounts', 'PageStatus')

    for status in ["processing", "redy", "in_progress", "done", "check", "formatting"]:
        PageStatus.objects.create(status=status)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_pagestatus_historicalpagestatus'),
    ]

    operations = [
        migrations.RunPython(create_statuses, reverse_code=migrations.RunPython.noop),
    ]
