# Generated by Django 4.2.7 on 2023-12-22 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0019_auto_20231217_1437'),
        ('accounts', '0006_auto_20231217_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'pages',
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.RegexValidator('^[0-9,-]+$')],
                        verbose_name='Страницы',
                    ),
                ),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignments',
                        to='books.book',
                        verbose_name='Книга',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assignments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
