# Generated by Django 4.2.7 on 2023-12-22 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначения'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pages',
            field=models.CharField(
                help_text='Номера страниц через запятую или диапазон через тире',
                max_length=100,
                validators=[django.core.validators.RegexValidator('^[0-9,-]+$')],
                verbose_name='Страницы',
            ),
        ),
    ]
